export const INCREAMENT_COUNTER = "INCREAMENT_COUNTER";
export const DECREAMENT_COUNTER = "DECREAMENT_COUNTER";
export const ADD_COUNTER = "ADD_COUNTER";
export const SUBTRACT_COUNTER = "SUBTRACT_COUNTER";
export const MULTIPLY_COUNTER = "MULTIPLY_COUNTER";
export const DIVIDE_COUNTER = "DIVIDE_COUNTER";
